application: wfdesk
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /static 
  static_dir: static
  secure: always
  
- url: /mif 
  static_dir: mif
  secure: always

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /index.php
  script: index.php
  secure: always
  
- url: /data.php
  script: data.php
  secure: always
  
- url: /login.php
  script: login.php
  secure: always
  
- url: /users.php
  script: users.php
  secure: always
  
- url: /logout.php
  script: logout.php
  secure: always

- url: /unauthorized.php
  script: unauthorized.php
  secure: always
  
- url: /*
  script: index.php
  secure: always
  
  

